spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: docker-cluster # defined in elasticsearch's image, see: https://blog.csdn.net/u012534326/article/details/99682162
    mongodb:
      uri: mongodb://mx1core:mx1core@localhost:27017/mx1core
mx1:
  binding: tcp://localhost:43210